server.port=8080
spring.application.name=gateway
spring.cloud.gateway.httpclient.pool.type=FIXED
spring.cloud.gateway.httpclient.pool.max-connections=200
spring.cloud.gateway.httpclient.pool.max-idle-time=5000
spring.cloud.gateway.httpclient.max-initial-line-length=3276800
spring.cloud.gateway.httpclient.max-header-size=3276800

# 启用访问日志
spring.cloud.gateway.httpclient.log.level=DEBUG
spring.cloud.gateway.httpclient.wiretap=true
spring.cloud.gateway.httpclient.wiretap.level=DEBUG

# 启用路由访问日志
logging.level.org.springframework.cloud.gateway=DEBUG

# Redis 配置
#spring.redis.host=${REDIS_HOST}
#spring.redis.port=${REDIS_PORT}
#spring.redis.password=${REDIS_PASSWORD}