{{- if .Values.dockerRegistry.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dockerRegistry.secretName }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "docker.config" . }}
{{- end }}

{{- define "docker.config" }}
{{- $registry := .Values.dockerRegistry.registry }}
{{- $username := .Values.dockerRegistry.username }}
{{- $password := .Values.dockerRegistry.password }}
{{- $email := .Values.dockerRegistry.email | default "" }}
{{- $auth := printf "%s:%s" $username $password | b64enc }}
{{- $config := dict "auths" (dict $registry (dict "username" $username "password" $password "email" $email "auth" $auth)) }}
{{- $config | toJson | b64enc }}
{{- end }} 