apiVersion: v1
kind: Secret
metadata:
  name: o11y-demo
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- range $key, $val := .Values.secret.data }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
