apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gateway
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
        armsPilotAutoEnable: "on"
        armsPilotCreateAppName: "gateway"
        armsSecAutoEnable: "on"
        acs.cms.workspace: "o11y-demo-cn-heyuan"
    spec:
      containers:
        - env:
            - name: JAVA_HOME
              value: /usr/local/openjdk-11
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: CONTAINER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
          image: 'o11y-demo-cn-heyuan-registry-vpc.cn-heyuan.cr.aliyuncs.com/o11y-demo-cn-heyuan/gateway:1.0'
          imagePullPolicy: Always
          name: gateway
          ports:
            - containerPort: 8080
              name: gateway
              protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  ports:
    - name: gateway
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: gateway
  type: ClusterIP