apiVersion: chaosblade.io/v1alpha1
kind: ChaosBlade
metadata:
  name: {{ .Name }}
spec:
  experiments:
    - scope: {{ .Scope }}
      target: mem
      action: load
      desc: "increase mem load by labels"
      matchers:
        - name: labels
          value: ["{{ .Labels }}"]
        - name: mem-percent
          value: ["{{ .Percent }}"]
        - name: timeout
          value: ["{{ .Timeout }}"]