apiVersion: chaosblade.io/v1alpha1
kind: ChaosBlade
metadata:
  name: {{ .Name }}
spec:
  experiments:
    - scope: {{ .Scope }}
      target: network
      action: loss
      desc: "network loss"
      matchers:
        - name: labels
          value: ["{{ .Labels }}"]
        - name: percent
          value:
            - "{{ .Percent }}"
        - name: interface
          value: ["eth0"]
        - name: timeout
          value: ["{{ .Timeout }}"]