apiVersion: chaosblade.io/v1alpha1
kind: ChaosBlade
metadata:
  name: mem-load
spec:
  experiments:
    - scope: pod
      target: mem
      action: load
      desc: "increase pod mem load by labels"
      matchers:
        - name: labels
          value: ["{{ .Labels }}"]
        - name: mem-percent
          value: ["{{ .Percent }}"]