spring:
  redis:
    host: ${REDIS_ADDR:redis}
    port: ${REDIS_PORT:6379}
    lettuce:
      pool:
        max-active: 8
        max-idle: 4
        min-idle: 1
        max-wait: 2000ms
    timeout: 5000ms
  cloud:
    gateway:
      httpclient:
        pool:
          max-idle-time: ${MAX_IDLE_TIME:5s}
      routes:
        - id: check
          uri: no://op
          predicates:
            - Path=/api/checkout**
          filters:
            - name: CheckFilter
              args:
                checkoutAddr: ${CHECKOUT_ADDR:localhost:50051}
                productAddr: ${PRODUCT_ADDR:localhost:50052}
        - id: getProduct
          uri: no://op
          predicates:
            - Path=/api/products/{productId}
          filters:
            - name: GetProduct
              args:
                productAddr: ${PRODUCT_ADDR:localhost:50051}
                currencyAddr: ${CURRENCY_ADDR:localhost:50052}
        - id: listProduct
          uri: no://op
          predicates:
            - Path=/api/products
          filters:
            - name: ListProduct
              args:
                productAddr: ${PRODUCT_ADDR:localhost:50051}
                currencyAddr: ${CURRENCY_ADDR:localhost:50052}
        - id: cart
          uri: no://op
          predicates:
            - Path=/api/cart
          filters:
            - name: Cart
              args:
                cartAddr: ${CART_ADDR}
                productAddr: ${PRODUCT_ADDR}
                currencyAddr: ${CURRENCY_ADDR}
        - id: data
          uri: no://op
          predicates:
            - Path=/api/data
          filters:
            - name: Data
              args:
                dataAddr: ${AD_ADDR}
        - id: recommendation
          uri: no://op
          predicates:
            - Path=/api/recommendations
          filters:
            - name: Recommendation
              args:
                recommendationAddr: ${RECOMMENDATION_ADDR}
                productAddr: ${PRODUCT_ADDR}
                currencyAddr: ${CURRENCY_ADDR}
        - id: currency
          uri: no://op
          predicates:
            - Path=/api/currency
          filters:
            - name: Currency
              args:
                currencyAddr: ${CURRENCY_ADDR}
        - id: ads
          uri: http://ads:8080
          predicates:
            - Path=/ads/**
        - id: feature
          uri: http://flagd-ui:8013
          predicates:
            - Path=/feature**
        - id: grafana
          uri: http://grafana:3000
          predicates:
            - Path=/grafana**
        - id: images
          uri: http://image-provider:8081
          predicates:
            - Path=/images/**
        - id: marketing
          uri: http://marketing:8080
          predicates:
            - Path=/marketing/**
        - id: notification
          uri: http://notification:8080
          predicates:
            - Path=/notification/**
        - id: user
          uri: http://user:8080
          predicates:
            - Path=/user/api/**
        - id: logistic-center
          uri: http://logistic-center:8080
          predicates:
            - Path=/logistic/**
        - id: order-center
          uri: http://order-center:8080
          predicates:
            - Path=/order/**
        - id: default
          uri: http://frontend:8080
          predicates:
            - Path=/**
          filters:
            - name: NoopFilter
server:
  port: 8085