spring:
  cloud:
    gateway:
      routes:
        - id: check
          uri: no://op
          predicates:
            - Path=/api/checkout**
          filters:
            - name: CheckFilter
              args:
                checkoutAddr: ${CHECKOUT_ADDR:localhost:50051}
                productAddr: ${PRODUCT_ADDR:localhost:50052}
        - id: getProduct
          uri: no://op
          predicates:
            - Path=/api/products/{productId}
          filters:
            - name: GetProduct
              args:
                productAddr: ${PRODUCT_ADDR:localhost:50051}
                currencyAddr: ${CURRENCY_ADDR:localhost:50052}
        - id: listProduct
          uri: no://op
          predicates:
            - Path=/api/products
          filters:
            - name: ListProduct
              args:
                productAddr: ${PRODUCT_ADDR:localhost:50051}
                currencyAddr: ${CURRENCY_ADDR:localhost:50052}
        - id: cart
          uri: no://op
          predicates:
            - Path=/api/cart
          filters:
            - name: Cart
              args:
                cartAddr: ${CART_ADDR}
                productAddr: ${PRODUCT_ADDR}
                currencyAddr: ${CURRENCY_ADDR}
        - id: ads
          uri: http://ads:8080
          predicates:
            - Path=/ads/**
        - id: feature
          uri: http://flagd-ui:8013
          predicates:
            - Path=/feature**
        - id: grafana
          uri: http://grafana:3000
          predicates:
            - Path=/grafana**
        - id: images
          uri: http://image-provider:8081
          predicates:
            - Path=/images/**
        - id: marketing
          uri: http://marketing:8080
          predicates:
            - Path=/marketing/**
        - id: notification
          uri: http://notification:8080
          predicates:
            - Path=/notification/**
        - id: default
          uri: http://frontend:8080
          predicates:
            - Path=/**
          filters:
            - name: NoopFilter
server:
  port: 8085