default:
  image:
    # 镜像仓库地址
    repository: <registryAdress>/<namespace>/<registryName>
    tag: "1.0"
    pullSecrets:
      # 镜像凭证Secret
      - name: demo
  # workspace
  workspace: <"workspace">
  # busybox 镜像仓库地址
  initContainers: "<registryAdress>/<namespace>/<registryName>/demo:latest-busybox"

secret:
  enabled: true
  data:
    #KAFKA_SERVICE_ADDR: "alikafka-post-cn-kvw46al4o00j-1-vpc.alikafka.aliyuncs.com:9092,alikafka-post-cn-kvw46al4o00j-2-vpc.alikafka.aliyuncs.com:9092,alikafka-post-cn-kvw46al4o00j-3-vpc.alikafka.aliyuncs.com:9092"
    MYSQL_ENDPOINT: "xxxxx.mysql.rds.aliyuncs.com:3306"
    MYSQL_PASSWORD: ""
    MYSQL_USER: "root"
    REDIS_ENDPOINT: ""
    REDIS_PASSWORD: ""
    ALIBABA_CLOUD_ACCESS_KEY_ID: ""
    ALIBABA_CLOUD_ACCESS_KEY_SECRET: ""
    ALIBABA_CLOUD_RUM_ENDPOINT: ""
    ALIBABA_CLOUD_RUM_PID: ""

chaosblade-operator:
  operator:
    # 镜像仓库地址
    repository: <registryAdress>/<namespace>/<registryName>
    version: latest-chaosblade-operator
    # image.pullPolicy: must be Always|IfNotPresent|Never
    pullPolicy: Always
    # 镜像凭证Secret
    pullSecrets: <demo>
    # qps of kubernetes client
    qps: 20
    reconcileCount: 20

  blade:
    # 镜像仓库地址
    repository: <registryAdress>/<namespace>/<registryName>
    version: latest-chaosblade-tool
    pullPolicy: Always
    # 镜像凭证Secret
    pullSecrets: <demo>
    downloadUrl: ""

prometheus:
  # 镜像凭证Secret
  imagePullSecrets:
    - name: <demo>
  server:
    image:
      # 镜像仓库地址
      repository: <registryAdress>/<namespace>/<registryName>
      tag: ""
      pullPolicy: Always

jaeger:
  allInOne:
    image:
      # 镜像仓库地址
      repository: <registryAdress>/<namespace>/<registryName>
      tag: ""
      pullPolicy: Always
      # 镜像凭证Secret
      pullSecrets:
        - name: <demo>

opensearch:
  image:
    # 镜像仓库地址
    repository: <registryAdress>/<namespace>/<registryName>
    tag: ""
    pullPolicy: Always
  # 镜像凭证Secret
  imagePullSecrets:
    - name: <demo>

opentelemetry-collector:
  image:
    # 镜像仓库地址
    repository: <registryAdress>/<namespace>/<registryName>
    tag: ""
    pullPolicy: Always
  # 镜像凭证Secret
  imagePullSecrets:
    - name: <demo>

components:
  flagd:
    schedulingRules:
      nodeSelector:
        # 为保证稳定，锁定在可用区b
        topology.kubernetes.io/zone: <cn-guangzhou-b>
  chaosblade-run:
    env:
      - name: ZONE
        # 模拟故障的可用区 （为保证稳定，请锁定为可用区a）
        value: <"cn-guangzhou-a">
      - name: NODEID
        # 模拟故障的实例id (为保证稳定，请在可用区a中选其一)
        value: <"i-7xvdyy7lka399nxi99o8">
    schedulingRules:
      nodeSelector:
        # 为保证稳定，锁定在可用区b
        topology.kubernetes.io/zone: <cn-guangzhou-b>