default:
  image:
    repository: o11y-demo-cn-heyuan-registry.cn-heyuan.cr.aliyuncs.com/o11y-demo-cn-heyuan/demo 
    tag: latest
    pullSecrets:
      - name: demo
components:
  marketing:
    labels:
      acs.cms.workspace: "your-workspace"
    imageOverride:
      repository: "o11y-demo-cn-heyuan-registry.cn-heyuan.cr.aliyuncs.com/o11y-demo-cn-heyuan/marketing"
      tag: "1.0"
  promotion:
    labels:
      acs.cms.workspace: "your-workspace"
    imageOverride:
      repository: "o11y-demo-cn-heyuan-registry.cn-heyuan.cr.aliyuncs.com/o11y-demo-cn-heyuan/promotion"
      tag: "1.0"
  notification:
    labels:
      acs.cms.workspace: "your-workspace"
    imageOverride:
      repository: "o11y-demo-cn-heyuan-registry.cn-heyuan.cr.aliyuncs.com/o11y-demo-cn-heyuan/notification"
      tag: "1.0"
  ads:
    labels:
      acs.cms.workspace: "your-workspace"
    imageOverride:
      repository: "o11y-demo-cn-heyuan-registry.cn-heyuan.cr.aliyuncs.com/o11y-demo-cn-heyuan/ads"
      tag: "1.0"
  valkey-cart:
    imageOverride:
      repository: "o11y-demo-cn-heyuan-registry.cn-heyuan.cr.aliyuncs.com/o11y-demo-cn-heyuan/valkey"
      tag: "7.2-alpine"
  accounting:
    initContainers:    
      - name: wait-for-kafka
        image: o11y-demo-cn-heyuan-registry.cn-heyuan.cr.aliyuncs.com/o11y-demo-cn-heyuan/busybox:latest
        command: ["sh", "-c", "until nc -z -v -w30 kafka 9092; do echo waiting for kafka; sleep 2; done;"]
  product-catalog:
    labels:
      acs.cms.workspace: "your-workspace"
  ad:
    labels:
      acs.cms.workspace: "your-workspace"
  recommendation:
    labels:
      acs.cms.workspace: "your-workspace"
  cart:
    initContainers:
      - name: wait-for-valkey-cart
        command: ["sh", "-c", "until nc -z -v -w30 valkey-cart 6379; do echo waiting for valkey-cart; sleep 2; done;"]
        image: o11y-demo-cn-heyuan-registry.cn-heyuan.cr.aliyuncs.com/o11y-demo-cn-heyuan/busybox:latest
  checkout:
    labels:
      acs.cms.workspace: "your-workspace"
    initContainers:
      - name: wait-for-kafka
        image: o11y-demo-cn-heyuan-registry.cn-heyuan.cr.aliyuncs.com/o11y-demo-cn-heyuan/busybox:latest
        command: ["sh", "-c", "until nc -z -v -w30 kafka 9092; do echo waiting for kafka; sleep 2; done;"]
  fraud-detection:
    labels:
      acs.cms.workspace: "your-workspace"
    initContainers:
      - name: wait-for-kafka
        image: o11y-demo-cn-heyuan-registry.cn-heyuan.cr.aliyuncs.com/o11y-demo-cn-heyuan/busybox
        command: ["sh", "-c", "until nc -z -v -w30 kafka 9092; do echo waiting for kafka; sleep 2; done;"]
  flagd:
    imageOverride:
      repository: "o11y-demo-cn-heyuan-registry.cn-heyuan.cr.aliyuncs.com/o11y-demo-cn-heyuan/flagd"
      tag: "v0.11.1"
    initContainers:
        - name: init-config
          image: o11y-demo-cn-heyuan-registry.cn-heyuan.cr.aliyuncs.com/o11y-demo-cn-heyuan/busybox
          command: ["sh", "-c", "cp /config-ro/demo.flagd.json /config-rw/demo.flagd.json && cat /config-rw/demo.flagd.json"]
          volumeMounts:
            - mountPath: /config-ro
              name: config-ro
            - mountPath: /config-rw
              name: config-rw
secret:
  enabled: true
  data:
    KAFKA_SERVICE_ADDR: "KAFKA_SERVICE_ADDR"
    MYSQL_ENDPOINT: "MYSQL_ENDPOINT"
    MYSQL_PASSWORD: "MYSQL_PASSWORD"
    MYSQL_USER: "MYSQL_USER"