apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: promotion
  name: promotion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promotion
  template:
    metadata:
      labels:
        app: promotion
        armsPilotAutoEnable: "on"
        armsPilotCreateAppName: "promotion-eks"
        armsSecAutoEnable: "on"
        acs.cms.workspace: "o11y-demo-cn-heyuan"
    spec:
      containers:
        - env:
            - name: JAVA_HOME
              value: /usr/local/openjdk-11
            - name: MYSQL_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: 011y-demo
                  key: MYSQL_ENDPOINT
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: 011y-demo
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: 011y-demo
                  key: MYSQL_PASSWORD
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: CONTAINER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
          image: 'ghcr.io/aliyun-sls/demo:latest-promotion-eks'
          imagePullPolicy: Always
          name: promotion
          ports:
            - containerPort: 8080
              name: promotion
              protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: promotion
spec:
  ports:
    - name: promotion
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: promotion
  type: ClusterIP